services:
  postgres:
    image: postgres:16
    container_name: telemetry-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: telemetry
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - telemetry-net

  ingestion-api:
    build:
      context: ./ingestion-api
    container_name: telemetry-ingestion-api
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/telemetry
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - telemetry-net

  data-generator:
    build:
      context: ./data-gen
    container_name: telemetry-data-generator
    environment:
      INGESTION_API_URL: http://ingestion-api:8080/api/v1/logs
    depends_on:
      - ingestion-api
    networks:
      - telemetry-net

  anomaly-worker:
    build:
      context: ./anomaly-worker
    container_name: telemetry-anomaly-worker
    environment:
      DB_USER: admin
      DB_PASS: password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: telemetry
      DISCORD_WEBHOOK_URL: https://discord.com/api/webhooks/1499788731677413407/R_75BYMXsGOurc8NkipZqCxz0eCnwF6QuSJGi4hWJ0FiQrgcWTEQptsy0l7yXLDzntlG
    depends_on:
      - postgres
    networks:
      - telemetry-net

  grafana:
    image: grafana/grafana:latest
    container_name: telemetry-grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - telemetry-net

networks:
  telemetry-net:
    driver: bridge
